  sample_rate: 16000
  log_prediction: true
  ctc_reduction: mean_volume
  skip_nan_grad: false
  train_ds:
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 20
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: fully_randomized
    bucketing_batch_size: null
  validation_ds:
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 32
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    max_duration: 20
  test_ds:
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
  tokenizer:
    dir: /tokenizers/NeMo_ASR_SET/English/asr_set_3.0/tokenizer_spe_unigram_v1024
    type: bpe
    model_path: nemo:0124d42f914e45e98c214bd5afd17f55_tokenizer.model
    vocab_path: nemo:129be3e4b71e449e86261ee42b6849fa_vocab.txt
    spe_tokenizer_vocab: nemo:7561592dab144ebaaade5d1244a9ffb0_tokenizer.vocab
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    normalize: per_feature
    window_size: 0.025
    window_stride: 0.01
    window: hann
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 1.0e-05
    pad_to: 0
    pad_value: 0.0
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: 80
    feat_out: -1
    n_layers: 18
    d_model: 512
    subsampling: dw_striding
    subsampling_factor: 8
    subsampling_conv_channels: 256
    causal_downsampling: false
    ff_expansion_factor: 4
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size:
    - -1
    - -1
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000
    conv_kernel_size: 9
    conv_norm_type: batch_norm
    conv_context_size: null
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 512
    num_classes: 1024
    vocabulary:
    - <unk>
    - s
    - ▁the
    - ▁a
    - t
    - ▁to
    - ▁and
    - ▁that
    - ''''
    - ▁of
    - ▁i
    - ▁in
    - d
    - ed
    - ing
    - ▁it
    - ▁you
    - 'n'
    - e
    - ▁is
    - 'y'
    - er
    - ▁for
    - m
    - ▁was
    - ▁we
    - re
    - ly
    - r
    - ▁he
    - ▁s
    - ▁be
    - c
    - ▁this
    - ▁so
    - ▁on
    - ▁have
    - g
    - a
    - ▁not
    - or
    - p
    - ▁they
    - ▁with
    - o
    - al
    - ▁but
    - ▁c
    - ▁are
    - ▁re
    - ▁there
    - ar
    - b
    - l
    - le
    - ▁know
    - ▁as
    - in
    - u
    - ▁what
    - ▁do
    - ▁or
    - ▁
    - ▁at
    - ation
    - w
    - ll
    - f
    - ▁one
    - ▁e
    - ▁f
    - ri
    - ▁if
    - ▁b
    - ent
    - ▁all
    - ▁de
    - ▁can
    - it
    - ▁would
    - ▁me
    - il
    - ▁like
    - ▁an
    - ce
    - ▁no
    - ▁t
    - ment
    - i
    - ve
    - k
    - ▁from
    - ▁just
    - ▁by
    - ▁his
    - ▁had
    - ion
    - ▁think
    - es
    - ch
    - 'on'
    - ▁about
    - th
    - ▁my
    - ck
    - en
    - ▁were
    - ▁your
    - ur
    - ▁will
    - ic
    - ▁go
    - ▁con
    - ▁she
    - li
    - an
    - ▁out
    - ter
    - ▁because
    - se
    - la
    - ▁when
    - ▁st
    - ▁has
    - ▁don
    - ▁which
    - ir
    - ra
    - ▁p
    - ▁two
    - ▁right
    - ▁court
    - ▁some
    - ▁pa
    - ▁pro
    - lo
    - ate
    - ▁time
    - ▁uh
    - te
    - ▁up
    - ▁our
    - ▁g
    - ▁case
    - ▁w
    - ▁her
    - ▁well
    - ro
    - ▁their
    - ▁who
    - ▁been
    - ▁yeah
    - ▁said
    - ers
    - ▁mo
    - ▁other
    - ▁see
    - ive
    - tion
    - el
    - ▁more
    - ▁se
    - vi
    - ▁any
    - ▁get
    - ▁also
    - ▁fa
    - ▁here
    - ▁un
    - ▁now
    - ▁co
    - ▁people
    - age
    - ist
    - ul
    - ▁how
    - ▁going
    - h
    - ▁very
    - ▁then
    - ▁could
    - de
    - ▁ma
    - ver
    - ▁mean
    - ▁su
    - id
    - ng
    - ▁lo
    - ▁sa
    - ▁la
    - ▁sp
    - ▁us
    - ol
    - ▁pre
    - ance
    - ▁want
    - ▁work
    - ld
    - ▁did
    - ge
    - ▁state
    - ▁po
    - ▁dis
    - ity
    - able
    - ▁say
    - ▁where
    - et
    - ▁ra
    - us
    - ▁li
    - ry
    - ction
    - ▁um
    - nd
    - ne
    - ▁even
    - ▁him
    - ▁ba
    - ad
    - ▁these
    - ▁part
    - ▁really
    - lu
    - ▁them
    - ▁those
    - ▁ho
    - v
    - ▁bo
    - ▁ex
    - ect
    - ▁over
    - ▁make
    - ru
    - ▁ro
    - is
    - ▁fi
    - ▁m
    - ut
    - ke
    - ence
    - ▁bu
    - ▁ch
    - ▁comp
    - me
    - ted
    - ▁en
    - ▁fact
    - z
    - ▁into
    - ▁need
    - ure
    - ▁way
    - ies
    - end
    - ▁mi
    - ▁take
    - un
    - ▁only
    - ▁should
    - as
    - ▁look
    - ▁three
    - one
    - ▁v
    - co
    - ▁com
    - ▁man
    - ta
    - ▁good
    - ated
    - ▁back
    - ▁first
    - ▁mr
    - ▁point
    - x
    - ▁new
    - ant
    - ▁vi
    - ▁dr
    - ff
    - ▁k
    - ci
    - ▁app
    - um
    - ▁n
    - ▁exp
    - ▁under
    - ▁after
    - po
    - ight
    - ▁d
    - est
    - mp
    - ▁okay
    - ine
    - ti
    - mo
    - qu
    - ▁da
    - ▁come
    - ▁day
    - ▁oh
    - ▁issue
    - at
    - ▁question
    - ▁than
    - ▁pri
    - ho
    - ten
    - ▁ca
    - ▁off
    - ain
    - ▁di
    - ▁o
    - ▁much
    - ▁five
    - ow
    - ▁ha
    - ▁thousand
    - ▁six
    - ▁give
    - ▁let
    - ▁le
    - ary
    - ous
    - sh
    - ▁yes
    - ▁four
    - ▁before
    - ▁call
    - ▁ga
    - ▁ne
    - ▁law
    - ma
    - ▁tra
    - ish
    - ical
    - ▁something
    - iv
    - ▁why
    - ▁may
    - ▁talk
    - ▁actually
    - ig
    - ▁act
    - ▁got
    - ▁car
    - ▁through
    - ful
    - ▁made
    - ▁hundred
    - om
    - man
    - ia
    - ▁didn
    - ual
    - ▁kind
    - ▁sta
    - ting
    - ▁things
    - ell
    - ▁down
    - im
    - ▁years
    - ▁lot
    - ▁ri
    - pe
    - ard
    - he
    - ▁gra
    - ▁year
    - ▁every
    - ▁eight
    - ▁reason
    - ▁seven
    - ca
    - ise
    - ▁twenty
    - ▁many
    - ▁per
    - op
    - ▁little
    - ▁mar
    - ▁same
    - ▁find
    - ▁different
    - ▁wa
    - pp
    - ▁nine
    - if
    - ▁does
    - ie
    - ach
    - cu
    - ▁never
    - ▁thing
    - ▁whether
    - ward
    - ▁again
    - ▁put
    - ▁claim
    - ▁op
    - ugh
    - ▁show
    - tic
    - ial
    - ▁still
    - ▁government
    - ok
    - ▁th
    - ▁long
    - ▁gu
    - ▁being
    - ▁plan
    - ▁own
    - am
    - ian
    - ▁evidence
    - ot
    - mb
    - ▁most
    - ▁ru
    - mit
    - ▁thank
    - ious
    - ▁person
    - em
    - ▁use
    - na
    - ▁sha
    - ▁r
    - ▁believe
    - mi
    - ▁school
    - ▁record
    - ition
    - ▁imp
    - ound
    - ▁place
    - ities
    - ▁happen
    - ▁ph
    - ▁great
    - ative
    - ha
    - 'no'
    - ▁cha
    - ite
    - ▁clear
    - ▁help
    - dic
    - ea
    - ▁high
    - ▁judge
    - ▁al
    - ▁last
    - di
    - qui
    - ▁sure
    - tra
    - go
    - ▁sh
    - ▁both
    - ▁read
    - ving
    - ▁district
    - ▁ref
    - ▁sub
    - ▁hi
    - ▁such
    - ▁ten
    - ▁start
    - ▁doesn
    - ph
    - ▁change
    - ay
    - ▁count
    - ▁ob
    - ▁found
    - ▁du
    - ▁ki
    - ▁pay
    - ▁order
    - ▁another
    - for
    - ▁hand
    - lic
    - ▁number
    - ▁too
    - ▁ta
    - ni
    - ens
    - ▁tell
    - ven
    - port
    - ▁fun
    - ▁h
    - ▁term
    - ▁end
    - rr
    - ▁must
    - ▁home
    - ▁hu
    - ▁wi
    - side
    - ▁certain
    - ▁name
    - ▁understand
    - ▁money
    - ize
    - ▁pu
    - ▁interest
    - ip
    - ▁came
    - ▁house
    - land
    - ▁men
    - ▁require
    - ▁says
    - min
    - ▁member
    - our
    - ating
    - ber
    - ▁jo
    - ▁might
    - vo
    - ▁support
    - ries
    - son
    - ▁problem
    - ling
    - ▁old
    - ▁pe
    - ▁second
    - ▁def
    - ness
    - ▁decision
    - row
    - ▁dollars
    - ▁mu
    - ▁conf
    - use
    - ▁ah
    - ▁va
    - ▁life
    - ▁inter
    - ▁play
    - va
    - ▁saying
    - ▁pi
    - ▁far
    - ▁went
    - ▁public
    - ▁war
    - ▁trans
    - ▁live
    - ▁ask
    - ▁real
    - rate
    - ▁important
    - ▁thought
    - ▁done
    - ▁between
    - ▁argument
    - ▁rep
    - ▁consider
    - ▁anything
    - ▁direct
    - less
    - ▁ja
    - ▁doing
    - ▁course
    - line
    - ▁month
    - ▁word
    - ▁care
    - ▁provide
    - ap
    - ▁honor
    - ba
    - ator
    - j
    - ▁report
    - ▁exc
    - ▁service
    - ▁tri
    - nk
    - ▁world
    - ▁without
    - ▁ju
    - ▁against
    - ible
    - ▁used
    - ▁always
    - ▁able
    - ship
    - ▁rule
    - ▁matter
    - ▁while
    - par
    - ▁maybe
    - ▁miss
    - ▁around
    - ▁u
    - ▁today
    - ▁friend
    - ▁ti
    - ▁big
    - bu
    - ▁next
    - ju
    - ▁thirty
    - ▁pass
    - ▁y
    - ▁business
    - ▁test
    - ▁fo
    - ▁nothing
    - ▁turn
    - ▁process
    - com
    - ▁el
    - ▁better
    - ▁commission
    - ▁week
    - ▁move
    - ▁trial
    - ▁open
    - ▁each
    - ▁specific
    - ▁feel
    - ▁cap
    - ency
    - ▁particular
    - ability
    - ▁system
    - gra
    - ▁present
    - ▁looking
    - duc
    - ▁fra
    - ▁correct
    - ▁allow
    - ▁side
    - ign
    - serv
    - ▁city
    - ▁agree
    - ▁having
    - ▁defendant
    - ▁keep
    - ▁follow
    - ▁invest
    - ▁add
    - ▁information
    - ▁whole
    - ▁general
    - hi
    - ▁away
    - ▁upon
    - ▁win
    - ▁based
    - ▁program
    - ▁develop
    - ▁country
    - ified
    - ▁sort
    - ▁board
    - ▁qua
    - ex
    - ▁family
    - ▁close
    - ▁dec
    - ▁though
    - ▁hard
    - ▁answer
    - ▁guess
    - ▁job
    - ▁trying
    - ▁je
    - ▁asked
    - ▁during
    - ▁fee
    - ▁love
    - ▁already
    - ▁address
    - ▁ever
    - ▁bill
    - gue
    - ▁cause
    - ▁gen
    - ▁free
    - ▁continue
    - ▁fifty
    - ▁contract
    - ▁european
    - ▁rest
    - ▁few
    - ▁water
    - ▁line
    - ▁position
    - ▁percent
    - ▁enough
    - ▁sea
    - ▁har
    - ▁america
    - ▁full
    - ▁since
    - ▁everything
    - ▁bring
    - ▁lead
    - ▁probably
    - ▁children
    - ▁tax
    - ▁face
    - ▁best
    - ▁concern
    - ▁sign
    - ▁mhm
    - ▁minute
    - ▁bit
    - ▁stand
    - ▁situation
    - ▁speak
    - ▁hope
    - ▁yet
    - ▁discuss
    - ▁standard
    - ▁brief
    - ▁statute
    - ▁officer
    - ▁ok
    - ▁respect
    - ▁together
    - ▁agreement
    - ▁room
    - ▁least
    - ▁market
    - ▁however
    - ▁getting
    - ▁else
    - ▁true
    - ▁counsel
    - ttle
    - ▁err
    - ▁effect
    - ▁example
    - ▁less
    - ▁cost
    - ▁left
    - ▁group
    - ▁level
    - ▁policy
    - ▁town
    - ▁small
    - ▁child
    - ▁president
    - ▁large
    - ▁later
    - ▁protect
    - ▁decide
    - way
    - ▁making
    - ▁regard
    - ▁book
    - ▁pretty
    - ▁author
    - ▁hour
    - ▁idea
    - ▁include
    - ▁exactly
    - ▁power
    - ▁limit
    - ▁watch
    - ▁night
    - ▁ya
    - ▁jury
    - ▁leave
    - ▁quite
    - ▁cover
    - ▁grow
    - ▁result
    - ▁singapore
    - ▁either
    - ▁company
    - ▁stop
    - ▁community
    - ▁million
    - ▁current
    - ▁federal
    - ▁united
    - ▁mind
    - ▁step
    - ▁class
    - ▁police
    - ▁remain
    - ▁health
    - ▁final
    - ▁represent
    - ▁light
    - ▁treat
    - ▁review
    - ▁testimony
    - ▁bank
    - ▁product
    - ▁appeal
    - ▁half
    - ▁cannot
    - ▁involve
    - ▁charge
    - ▁knew
    - ▁learn
    - ▁eye
    - ▁language
    - ▁individual
    - ▁receive
    - ▁further
    - ▁mister
    - ▁view
    - ▁council
    - ▁until
    - ▁human
    - ▁stuff
    - ▁student
    - ▁become
    - ▁walk
    - ▁control
    - ▁check
    - ▁seems
    - ▁strong
    - ▁period
    - ▁please
    - ▁food
    - ▁type
    - ▁complete
    - ▁purpose
    - ▁account
    - ▁project
    - ▁sense
    - ▁national
    - ▁appear
    - ▁simply
    - ▁return
    - ▁benefit
    - ▁employ
    - ▁create
    - ▁wrong
    - ▁whatever
    - ▁morning
    - ▁suggest
    - ▁condition
    - ▁amount
    - ▁object
    - ▁third
    - ▁remember
    - ▁himself
    - ▁property
    - ▁itself
    - ▁somebody
    - ▁suppose
    - ▁future
    - ▁short
    - ▁opinion
    - ▁several
    - ▁common
    - ▁taking
    - ▁notice
    - ▁office
    - ▁almost
    - ▁father
    - ▁document
    - ▁judgment
    - ▁experience
    - ▁uhhuh
    - ▁committee
    - ▁parent
    - ▁legal
    - ▁client
    - ▁major
    - ▁congress
    - ▁rather
    - ▁proceed
    - ▁possible
    - ▁plea
    - ▁subject
    - ▁along
    - ▁mother
    - ▁increase
    - ▁meeting
    - ▁girl
    - ▁couple
    - ▁north
    - ▁local
    - ▁sometimes
    - ▁brought
    - ▁fifteen
    - ▁organ
    - ▁difference
    - ▁entire
    - ▁security
    - ▁department
    - ▁south
    - ▁vote
    - ▁basis
    - ▁twelve
    - ▁conduct
    - ▁street
    - ▁social
    - ▁wonder
    - ▁supreme
    - ▁difficult
    - ▁travel
    - ▁opportunity
    - ▁defense
    - ▁plaintiff
    - ▁white
    - ▁focus
    - ▁therefore
    - ▁challenge
    - ▁value
    - ▁except
    - ▁among
    - ▁ground
    - ▁serve
    - ▁attorney
    - ▁education
    - ▁credit
    - ▁request
    - ▁women
    - ▁basically
    - ▁political
    - ▁determine
    - ▁access
    - ▁across
    - ▁sentence
    - ▁perform
    - ▁everybody
    - ▁black
    - ▁drug
    - ▁accept
    - ▁eleven
    - ▁establish
    - ▁design
    - ▁success
    - ▁including
    - ▁john
    - ▁employee
    - ▁nice
    - ▁crime
    - ibility
    - ▁circumstance
    - ▁occur
    - ▁citizen
    - ▁woman
    - ▁witness
    - ▁explain
    - ▁additional
    - ▁history
    - ▁front
    - ▁medical
    - ▁death
    - ification
    - ▁financial
    - ▁break
    - ▁connect
    - ▁perhaps
    - ▁sorry
    - ▁especially
    - ▁trust
    - ▁insurance
    - ▁economic
    - ▁effort
    - ▁circuit
    - ▁cross
    - ▁instead
    - ▁affect
    - ▁zero
    - ▁available
    - ▁team
    - ▁application
    - ▁separate
    - ▁absolutely
    - ▁christ
    - ization
    - ▁europe
    - ▁budget
    - ▁damage
    - ▁myself
    - ▁private
    - ▁figure
    - ▁provision
    - ▁collect
    - ▁similar
    - ▁regulation
    - ▁approach
    - ▁themselves
    - ▁construct
    - ▁petition
    - ▁material
    - ▁improve
    - ▁york
    - ▁parliament
    - ▁broad
    - ▁companies
    - ▁nature
    - ▁piece
    - ▁threat
    - ▁energy
    - ▁behind
    - ▁significant
    - ▁response
    - ▁definitely
    - ▁guide
    - ▁beyond
    - ▁amendment
    - ▁measure
    - ▁criminal
    - ▁original
    - ▁brother
    - ▁impact
    - q
  optim:
    name: adamw
    lr: 0.001
    betas:
    - 0.9
    - 0.98
    weight_decay: 0.001
    sched:
      name: CosineAnnealing
      warmup_steps: 15000
      warmup_ratio: null
      min_lr: 0.0001
  target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
  nemo_version: 1.13.0rc0
  decoding:
    strategy: greedy
    preserve_alignments: null
    compute_timestamps: null
    confidence_cfg:
      preserve_frame_confidence: false
      preserve_token_confidence: false
      preserve_word_confidence: false
      exclude_blank: true
      aggregation: min
      method_cfg:
        name: entropy
        entropy_type: tsallis
        temperature: 0.33
        entropy_norm: exp
    word_seperator: ' '
    ctc_timestamp_type: all
    batch_dim_index: 0
    greedy:
      preserve_alignments: false
      compute_timestamps: false
      preserve_frame_confidence: false
      confidence_method_cfg: null
